(source (official lib))
(config username "nyi nyi thann")
(config project_name unicode-zawgyi-converter)
(config npm_username nyinyithann)
(config github_username nyinyithann)
(config project_description
 "Converter for Myanmar (Burmese) unicode text to zawgyi text, and vice versa")
(config package_manager Opam)
(config ci_cd Github)
(config syntax OCaml)
(config project_snake unicode_zawgyi_converter)
(config project_slug unicode-zawgyi-converter)
(config test_framework Alcotest)
